# trigger:

# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Microsoft Partner Network (55cf0ba9-e3c1-4ced-b5e9-5abb7b4d39b1)
  resourceGroup: Team_AWS
  storageAccount: terraformtfstateskip
  container: tfstatefile
  tfstateFile: terraform.tfstate
  anyTfChanges: false

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    backendServiceArm: 'Microsoft Partner Network (55cf0ba9-e3c1-4ced-b5e9-5abb7b4d39b1)'
    backendAzureRmResourceGroupName: 'Team_AWS'
    backendAzureRmStorageAccountName: 'terraformstateskip'
    backendAzureRmContainerName: 'tfstatefile'
    backendAzureRmKey: 'tfstatefile'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/skip-step'
    environmentServiceNameAzureRM: 'Microsoft Partner Network (55cf0ba9-e3c1-4ced-b5e9-5abb7b4d39b1)'

